pub mod audio;
pub mod cli;
pub mod commands;
pub mod config;
pub mod monitoring;
pub mod recorder;
pub mod storage;
pub mod summarize;
pub mod transcribe;
pub mod setup;
#[cfg(target_os = "windows")]
pub mod tray;
